### ISSUE TITLE
No way to find version of installed binary

### ISSUE THREAD

**Issue by EspadaV8** [openpixel/rise#4]
Would it be possible to add a `-v` and/or `--version` flag that returns the currently installed version please.

**Comment by cam-stitt** [comment]
Sure thing. I had it on my road map, but was waiting until I'd finalized how the var flag was going to work.

**Comment by cam-stitt** [comment]
The latest release has added a version command. You can now see the version by running `rise version`.

**Comment by EspadaV8** [comment]
Awesome. Thank you 😀

**Comment by cam-stitt** [comment]
No problems at all. Thanks for being the first person to submit an issue! If you have any feedback at all, I would love to hear it.
